### PR TITLE
release lock when sending from ice to avoid deadlocking with turnConn…

### LINKED ISSUE #172: Fix potential deadlocks in IceAgent interlocking with TurnConnection lock
Issue https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/165 is a particular instance. There are couple of other call sites that need to be properly handled in IceAgent.c

### LINKED ISSUE #207: Dead lock in TurnConnection.c
On ARM platform, when receiving remote Ice candidates, kvs could run into deadlock in TurnConnection.c.  The failure rate is about 20% for my set up.
Somehow, when turnConnectionTimerCallback is called, mutex is locked but never unlocked. 
When another ice candidate comes and turnConnectionAddPeer is called, it fails to lock the mutex. 
ice related code is stuck here.  SRTP initialization never finishes

### PR DESCRIPTION
**Pull request by chehefen**
…ection

*Issue #, if available:*
resolves #207 
resolves #172 

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: tst/PeerConnectionFunctionalityTest.cpp [hunk 1]
```diff
@@ -214,6 +181,102 @@ TEST_F(PeerConnectionFunctionalityTest, exchangeMedia)
...
+        UINT64 streamingTimeMs;
+        RtcConfiguration configuration;
+
+        MEMSET(&videoFrame, 0x00, SIZEOF(Frame));
+        videoFrame.frameData = (PBYTE) MEMALLOC(frameBufferSize);
+        videoFrame.size = TEST_VIDEO_FRAME_SIZE;
+        MEMSET(videoFrame.frameData, 0x11, videoFrame.size);
+
+        for(int i = 0; i < iteration; ++i) {
+            printf("/////////////////////////////////////////////////////////////\n"
```
Comment (Sean-Der) [inline tst/PeerConnectionFunctionalityTest.cpp]: Mind removing the printf

File: tst/PeerConnectionFunctionalityTest.cpp [hunk 2]
```diff
@@ -214,6 +181,102 @@ TEST_F(PeerConnectionFunctionalityTest, exchangeMedia)
...
+        Frame videoFrame;
+        PRtcPeerConnection offerPc = NULL, answerPc = NULL;
+        RtcMediaStreamTrack offerVideoTrack, answerVideoTrack, offerAudioTrack, answerAudioTrack;
+        PRtcRtpTransceiver offerVideoTransceiver, answerVideoTransceiver, offerAudioTransceiver, answerAudioTransceiver;
+        ATOMIC_BOOL offerSeenVideo = 0, answerSeenVideo = 0, offerStopVideo = 0, answerStopVideo = 0;
+        UINT64 streamingTimeMs;
+        RtcConfiguration configuration;
+
+        MEMSET(&videoFrame, 0x00, SIZEOF(Frame));
+        videoFrame.frameData = (PBYTE) MEMALLOC(frameBufferSize);
```
Comment (Sean-Der) [inline tst/PeerConnectionFunctionalityTest.cpp]: `unique_ptr` possible?

**Comment by Sean-Der** [comment]
I am glad this is getting more extensively tested, but it feels pretty scary how many places we have `assume holding lock` and have callees unlock/re-lock stuff.

Long term would love to know all the state we are locking for (and if we can do swaps/gets instead)

File: src/source/Ice/IceAgentStateMachine.c [hunk 3]
```diff
@@ -732,8 +732,8 @@ STATUS executeDisconnectedIceAgentState(UINT64 customData, UINT64 time)
         pIceAgent->iceAgentCallbacks.connectionStateChangedFn(pIceAgent->customData, ICE_AGENT_STATE_DISCONNECTED);
     }
 
-    // step out of disconnection state to retry
-    CHK_STATUS(stepIceAgentStateMachine(pIceAgent));
+    // step out of disconnection state to retry. Do not use stepIceAgentState machine because lock is not re-entrant.
```
Comment (MushMal) [inline src/source/Ice/IceAgentStateMachine.c]: Re-wording the comment - perhaps this means that this might be run from another thread that already holds the lock?

Comment (MushMal) [reply src/source/Ice/IceAgentStateMachine.c]: BTW, could this be easier solved by making the lock re-entrant?

Comment (chehefen) [reply src/source/Ice/IceAgentStateMachine.c]: I purposely made the lock non re-entrant so that I dont have to deal with multiple layers of unlocking.

File: src/source/Ice/IceAgent.c [hunk 4]
```diff
@@ -1444,8 +1484,14 @@ STATUS iceAgentReadyStateSetup(PIceAgent pIceAgent)
     // no state timeout for ready state
     pIceAgent->stateEndTime = INVALID_TIMESTAMP_VALUE;
 
+    relayCandidateSelected = IS_CANN_PAIR_SENDING_FROM_RELAYED(pIceAgent->pDataSendingIceCandidatePair);
+
+    // unlock ice lock before calling turn api.
+    MUTEX_UNLOCK(pIceAgent->lock);
```
Comment (MushMal) [inline src/source/Ice/IceAgent.c]: This is a race condition case and a layer violation. Also, you would rather unlock inside the if statement. Is there any other simple way to handle this case in the outer functionality outside of the lock?

It might not be neat but think if the timer queue can be scheduled for this

Comment (chehefen) [reply src/source/Ice/IceAgent.c]: removed the locking. IceAgent can now call turnConnection while holding the iceAgent lock because I made turnConnection to release its lock before triggering ice api. So there is no more circular locking.

**Comment by alexw91** [comment]
# [Codecov](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214?src=pr&el=h1) Report
> Merging [#214](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214?src=pr&el=desc) into [master](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/82c6db6be962e2a8def50a5cda170d600fab010e&el=desc) will **decrease** coverage by `0.06%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #214      +/-   ##
==========================================
- Coverage   86.96%   86.89%   -0.07%     
==========================================
  Files          33       33              
  Lines        7717     7807      +90     
==========================================
+ Hits         6711     6784      +73     
- Misses       1006     1023      +17     
```


| [Impacted Files](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/source/Ice/IceAgent.c](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214/diff?src=pr&el=tree#diff-c3JjL3NvdXJjZS9JY2UvSWNlQWdlbnQuYw==) | `93.99% <0.00%> (+0.39%)` | :arrow_up: |
| [src/source/PeerConnection/PeerConnection.c](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214/diff?src=pr&el=tree#diff-c3JjL3NvdXJjZS9QZWVyQ29ubmVjdGlvbi9QZWVyQ29ubmVjdGlvbi5j) | `93.90% <0.00%> (+0.21%)` | :arrow_up: |
| [src/source/Ice/TurnConnection.c](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214/diff?src=pr&el=tree#diff-c3JjL3NvdXJjZS9JY2UvVHVybkNvbm5lY3Rpb24uYw==) | `91.74% <0.00%> (-0.09%)` | :arrow_down: |
| [src/source/Ice/IceAgentStateMachine.c](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214/diff?src=pr&el=tree#diff-c3JjL3NvdXJjZS9JY2UvSWNlQWdlbnRTdGF0ZU1hY2hpbmUuYw==) | `83.33% <0.00%> (+0.29%)` | :arrow_up: |
| [src/source/Ice/SocketConnection.c](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214/diff?src=pr&el=tree#diff-c3JjL3NvdXJjZS9JY2UvU29ja2V0Q29ubmVjdGlvbi5j) | `81.59% <0.00%> (-1.09%)` | :arrow_down: |
| [src/source/PeerConnection/Rtp.c](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214/diff?src=pr&el=tree#diff-c3JjL3NvdXJjZS9QZWVyQ29ubmVjdGlvbi9SdHAuYw==) | `72.66% <0.00%> (-2.70%)` | :arrow_down: |
| [src/source/Stun/Stun.c](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214/diff?src=pr&el=tree#diff-c3JjL3NvdXJjZS9TdHVuL1N0dW4uYw==) | `86.09% <0.00%> (+1.70%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214?src=pr&el=footer). Last update [2a690f1...bf73347](https://codecov.io/gh/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/214?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
