### PR TITLE
Fix FireFox compatibility issues

### LINKED ISSUE #26: Fix FireFox compatibility
Not sure what the issues are yet, currently unable to connect with FireFox though.

### PR DESCRIPTION
**Pull request by Sean-Der**
* SDP Deserialize now properly handles Media ConnectionInformation
* Don't set Reduced Size RTCP attribute. We don't emit RTCP at all currently

Resolves #26

### CODE REVIEW

File: src/source/Sdp/Deserialize.c [hunk 1]
```diff
@@ -164,6 +164,34 @@ STATUS deserializeMediaName(PCHAR pMediaName, PCHAR *ppOutputData, PUINT32 pTota
     return retStatus;
 }
 
+STATUS deserializeMediaConnectionInformation(PSdpConnectionInformation pSdpConnectionInformation, PCHAR *ppOutputData, PUINT32 pTotalWritten, PUINT32 pBufferSize)
+{
+    ENTERS();
+    STATUS retStatus = STATUS_SUCCESS;
+    UINT32 currentWriteSize = 0;
+
+    if (pSdpConnectionInformation->networkType[0] != '\0') {
```
Comment (MushMal) [inline src/source/Sdp/Deserialize.c]: Assuming that the parameters have been sanitized before this function call
