### PR TITLE
configure socket to not emit SIG_PIPE

### LINKED ISSUE #321: Segfault establishing Turn Connection
Observed pretty frequently in devices
```
2020-03-31 16:11:23 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-03-31 16:11:26 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 10
2020-03-31 16:11:26 DEBUG   lwsWssCallbackRoutine(): Client is writable
2020-03-31 16:11:26 VERBOSE lwsWssCallbackRoutine(): WSS callback with reason 9
2020-03-31 16:11:28 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-03-31 16:11:33 INFO    signalingClientGetCurrentState(): Signaling Client Get Current State
2020-03-31 16:11:34 WARN    connectionListenerReceiveDataRoutine(): recvfrom() failed with errno Connection reset by peer
--Type <RET> for more, q to quit, c to continue without paging--

Thread 64 "alexa_webrtc" received signal SIGPIPE, Broken pipe.
[Switching to LWP 31008]
0x76ab70a0 in write () from /lib/libpthread.so.0
(gdb) bt full
#0  0x76ab70a0 in write () from /lib/libpthread.so.0
No symbol table info available.
#1  0x76bdaa1a in fd_write () from /mnt/plugin/alexa_webrtc/lib/libcrypto.so.1.1
No symbol table info available.
#2  0x76bd7018 in BIO_write () from /mnt/plugin/alexa_webrtc/lib/libcrypto.so.1.1
No symbol table info available.
#3  0x76b3d078 in ssl3_write_pending () from /mnt/plugin/alexa_webrtc/lib/libssl.so.1.1
No symbol table info available.
#4  0x76b3d848 in ssl3_write_bytes () from /mnt/plugin/alexa_webrtc/lib/libssl.so.1.1
No symbol table info available.
#5  0x76b48e16 in SSL_write () from /mnt/plugin/alexa_webrtc/lib/libssl.so.1.1
No symbol table info available.
#6  0x76fb1916 in socketConnectionSendData () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#7  0x76fb25d8 in turnConnectionSendData () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#8  0x76fb0bb4 in iceUtilsSendData () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#9  0x76fad934 in iceAgentSendStunPacket () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#10 0x76fada5c in iceCandidatePairCheckConnection () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#11 0x76fadd96 in iceAgentCheckCandidatePairConnection () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#12 0x76fb0332 in executeCheckConnectionIceAgentState () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#13 0x76fc061e in stepStateMachine () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#14 0x76fb0738 in stepIceAgentStateMachine () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#15 0x76fadbda in iceAgentStateTransitionTimerCallback () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#16 0x76fbfd48 in timerQueueExecutor () from /mnt/plugin/alexa_webrtc/lib/libkvsWebrtcClient.so
No symbol table info available.
#17 0x76ab0780 in ?? () from /lib/libpthread.so.0
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

### PR DESCRIPTION
**Pull request by chehefen**
*Issue #, if available:*
fix #321 
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/source/Ice/SocketConnection.c [hunk 1]
```diff
@@ -155,37 +160,75 @@ STATUS socketConnectionSendData(PSocketConnection pSocketConnection, PBYTE pBuf,
...
+                    case SSL_ERROR_WANT_WRITE:
+                        break;
+                    default:
+                        DLOGW("SSL_write failed with %s", ERR_error_string(sslErr, NULL));
+                        DLOGD("Close socket %d", pSocketConnection->localSocket);
+                        ATOMIC_STORE_BOOL(&pSocketConnection->connectionClosed, TRUE);
+                        break;
+                }
+
+                CHK(FALSE, STATUS_SEND_DATA_FAILED);
```
Comment (MushMal) [inline src/source/Ice/SocketConnection.c:192]: Do we want to error out with STATUS_SEND_DATA_FAILED on want read/write?

File: src/source/Ice/SocketConnection.c [hunk 2]
```diff
@@ -155,37 +160,75 @@ STATUS socketConnectionSendData(PSocketConnection pSocketConnection, PBYTE pBuf,
...
+                DLOGD("Close socket %d", pSocketConnection->localSocket);
+                ATOMIC_STORE_BOOL(&pSocketConnection->connectionClosed, TRUE);
+            }
+
+            /* need to also reset BIO on negative path */
+            retStatus = STATUS_SEND_DATA_FAILED;
         }
 
+        /* reset bio to clear its content since it's already sent */
+        BIO_reset(SSL_get_wbio(pSocketConnection->pSsl));
```
Comment (MushMal) [inline src/source/Ice/SocketConnection.c:211]: It's cleaner to handle this in the cleanup

File: src/source/Ice/SocketConnection.c [hunk 3]
```diff
@@ -155,37 +160,75 @@ STATUS socketConnectionSendData(PSocketConnection pSocketConnection, PBYTE pBuf,
...
+
     } else if (pSocketConnection->protocol == KVS_SOCKET_PROTOCOL_TCP) {
-        if (send(pSocketConnection->localSocket, pBuf, bufLen, 0) < 0) {
+        /* Should have a valid buffer */
+        CHK(pBuf != NULL && bufLen > 0, STATUS_INVALID_ARG);
```
Comment (MushMal) [inline src/source/Ice/SocketConnection.c:215]: Why is this check not done once in the beginning?

File: src/source/Ice/SocketConnection.c [hunk 4]
```diff
@@ -226,6 +269,12 @@ STATUS socketConnectionSendData(PSocketConnection pSocketConnection, PBYTE pBuf,
         }
         if (result < 0) {
             DLOGD("sendto data failed with errno %s", strerror(errno));
+
+            if (!socketShouldRetry(errno)) {
+                DLOGD("Close socket %d", pSocketConnection->localSocket);
+                ATOMIC_STORE_BOOL(&pSocketConnection->connectionClosed, TRUE);
+            }
+
             CHK(FALSE, STATUS_SEND_DATA_FAILED);
```
Comment (MushMal) [inline src/source/Ice/SocketConnection.c:278]: This is a repeated pattern - either MACRO it out or have an inline function

File: src/source/Ice/SocketConnection.c [hunk 5]
```diff
@@ -350,3 +409,16 @@ INT32 certificateVerifyCallback(INT32 preverify_ok, X509_STORE_CTX *ctx)
     UNUSED_PARAM(ctx);
     return 1;
 }
+
+BOOL socketShouldRetry(INT32 err)
```
Comment (MushMal) [inline src/source/Ice/SocketConnection.c:413]: Make this as a macro

File: src/source/Ice/TurnConnection.c [hunk 6]
```diff
@@ -1086,11 +1087,17 @@ STATUS turnConnectionStepState(PTurnConnection pTurnConnection)
             break;
     }
 
+    if (socketConnectionIsClosed(pTurnConnection->pControlChannel)) {
+        DLOGE("TurnConnection socket %d closed unexpectedly", pTurnConnection->pControlChannel->localSocket);
+        /* trigger transition to TURN_STATE_FAILED */
+        retStatus = STATUS_SOCKET_CONNECTION_CLOSED_ALREADY;
```
Comment (MushMal) [inline src/source/Ice/TurnConnection.c:1093]: You can use CHK_ERR

File: src/source/Ice/SocketConnection.c [hunk 7]
```diff
@@ -121,16 +121,21 @@ STATUS socketConnectionInitSecureConnection(PSocketConnection pSocketConnection,
     }
 
     SSL_set_mode(pSocketConnection->pSsl, SSL_MODE_AUTO_RETRY);
-    CHK((pSocketConnection->pWriteBio = BIO_new_fd(pSocketConnection->localSocket, BIO_NOCLOSE)) != NULL, STATUS_SSL_CTX_CREATION_FAILED);
     CHK((pSocketConnection->pReadBio = BIO_new(BIO_s_mem())) != NULL, STATUS_SSL_CTX_CREATION_FAILED);
+    CHK((pSocketConnection->pWriteBio = BIO_new(BIO_s_mem())) != NULL, STATUS_SSL_CTX_CREATION_FAILED);
```
[the remark this answers is not in the document]
Comment (chehefen) [reply src/source/Ice/SocketConnection.c:125]: these is related actually. Previously we use a fd Bio which writes to the socket directly. But since we need to also pass the NO_SIGNAL flag to send(), and openssl doenst expose that through SSL_write, we have to switch to use a mem bio instead and do the send ourselves.

File: src/source/Ice/SocketConnection.c (hunk 1 above)
Comment (chehefen) [reply src/source/Ice/SocketConnection.c:192]: the STATUS_SEND_DATA_FAILED does get handled by its callers.

File: src/source/Ice/SocketConnection.c (hunk 2 above)
Comment (chehefen) [reply src/source/Ice/SocketConnection.c:211]: I dont quite get how it's cleaner. It makes sense locality wise because we did BIO_get_mem_data, we should clear the content from the BIO by doing BIO_reset.

File: src/source/Ice/SocketConnection.c (hunk 3 above)
Comment (chehefen) [reply src/source/Ice/SocketConnection.c:215]: because I also use this function to send handshake bits that ssl generates internally after SSL_do_handshake. In that case there is no application data.

File: src/source/Ice/SocketConnection.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (MushMal) [reply src/source/Ice/SocketConnection.c:125]: I see, makes sense now.

File: src/source/Ice/SocketConnection.c (hunk 2 above)
Comment (MushMal) [reply src/source/Ice/SocketConnection.c:206]: I disagree. The clean-up clause is entirely designed for that purpose. The entire codebase adheres to this constructs. If something needs to be cleaned up it's cleaned up in the cleanup clause. If the function is logically complex to not allow it then we need to see if the function needs to be broken down.

The main issue with premature cleanup is the code maintenance. Within the next few iterations, inevitably, code will be inserted that will make the logic of early cleanup more complex.

This all said, if you feel that it's very targeted and local then go ahead.

File: src/source/Ice/SocketConnection.c (hunk 3 above)
Comment (MushMal) [reply src/source/Ice/SocketConnection.c:210]: So, in that case we still have the size param but buffer is NULL?

File: src/source/Ice/SocketConnection.c (hunk 2 above)
Comment (chehefen) [reply src/source/Ice/SocketConnection.c:206]: yh it's very targeted to TCP TLS only. If we put it in cleanup, we need to do vigorous check that it was TCP TLS, and it wasnt bailing for thing like STATUS_NULL_ARG or STATUS_INVALID_ARG.

File: src/source/Ice/SocketConnection.c (hunk 3 above)
Comment (chehefen) [reply src/source/Ice/SocketConnection.c:210]: size is 0 and buffer is NULL.

Comment (MushMal) [reply src/source/Ice/SocketConnection.c:210]: I see.. Do we need to add a check for when size is not 0 then buffer should not be NULL?

Comment (chehefen) [reply src/source/Ice/SocketConnection.c:210]: so it's either SSL init is not finished in which case pBuf and bufLen are completely ignored, or it's sending application data and thus pBuf != NULL and bufLen > 0.
